# Development Environment Properties
spring.config.import=optional:configserver:http://localhost:8071/

# Eureka Instance Configuration for Local Development
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
