# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.hikari.schema=laon
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true



# Use the 'loan' schema
spring.jpa.properties.hibernate.default_schema=loan

# Set JDBC time zone to UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Active profile
spring.profiles.active=dev
